import 'dotenv/config'
import express from 'express'
import cors from 'cors'
import helmet from 'helmet'
import rateLimit from 'express-rate-limit'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import multer from 'multer'
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import mysql from 'mysql2/promise'

const app = express()
const port = Number(process.env.PORT || 3001)
const uploadDir = path.resolve(process.env.UPLOAD_DIR || 'private-uploads')
fs.mkdirSync(uploadDir, { recursive: true })
const pool = mysql.createPool({ uri: process.env.DATABASE_URL, waitForConnections: true, connectionLimit: 10 })
const upload = multer({ dest: uploadDir, limits: { fileSize: 25 * 1024 * 1024 }, fileFilter: (_req, file, cb) => cb(null, /^(image|application\/pdf)/.test(file.mimetype)) })

app.use(helmet({ crossOriginResourcePolicy: false }))
app.use(cors({ origin: process.env.FRONTEND_ORIGIN || true }))
app.use(express.json({ limit: '2mb' }))
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 300 }))

const publicOrderId = () => `MXZ-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(2).toString('hex').toUpperCase()}`
const tokenFor = user => jwt.sign({ id: user.id, role: user.role, name: user.name }, process.env.SESSION_SECRET, { expiresIn: '12h' })
function auth(req, res, next) { try { req.user = jwt.verify((req.headers.authorization || '').replace('Bearer ', ''), process.env.SESSION_SECRET); next() } catch { res.status(401).json({ error: 'Authentication required' }) } }
function roles(...allowed) { return (req, res, next) => allowed.includes(req.user.role) ? next() : res.status(403).json({ error: 'Insufficient permissions' }) }
async function event(orderId, actorId, status, note = '') { await pool.query('INSERT INTO order_events (order_id, actor_id, status, note) VALUES (?, ?, ?, ?)', [orderId, actorId || null, status, note]) }

app.get('/api/health', (_req, res) => res.json({ ok: true, service: 'maxrez-api' }))
app.get('/api/setup/status', async (_req, res) => { try { const [rows] = await pool.query('SHOW TABLES LIKE "users"'); if (!rows.length) return res.json({ ready: false }); const [users] = await pool.query('SELECT COUNT(*) count FROM users'); res.json({ ready: Number(users[0].count) > 0, configured: Number(users[0].count) > 0 }) } catch { res.json({ ready: false, database: false }) } })
app.post('/api/setup', async (req, res) => { const { setupKey, adminName, adminEmail, adminPassword, paymentMethods = [], deliveryZones = [] } = req.body; if (!process.env.SETUP_KEY || setupKey !== process.env.SETUP_KEY) return res.status(403).json({ error: 'Invalid setup key' }); if (!adminName || !adminEmail || !adminPassword || adminPassword.length < 10) return res.status(400).json({ error: 'Admin name, email, and a password of at least 10 characters are required' }); const schema = fs.readFileSync(path.resolve('server/schema.sql'), 'utf8'); const connection = await pool.getConnection(); try { await connection.beginTransaction(); for (const statement of schema.split(';').map(s => s.trim()).filter(Boolean)) await connection.query(statement); const [existing] = await connection.query('SELECT COUNT(*) count FROM users'); if (Number(existing[0].count) > 0) return res.status(409).json({ error: 'Setup has already been completed' }); const hash = await bcrypt.hash(adminPassword, 12); await connection.query('INSERT INTO users (name, email, password_hash, role) VALUES (?, ?, ?, "admin")', [adminName, adminEmail, hash]); for (const method of paymentMethods.filter(p => p.name && p.accountLabel)) await connection.query('INSERT INTO payment_methods (name, instructions, account_label, active, sort_order) VALUES (?, ?, ?, 1, ?)', [method.name, method.instructions || 'Pay using the account shown and upload your receipt.', method.accountLabel, method.sortOrder || 0]); await connection.commit(); fs.writeFileSync(path.resolve('setup-config.json'), JSON.stringify({ deliveryZones, configuredAt: new Date().toISOString() }, null, 2)); res.json({ ok: true }) } catch (error) { await connection.rollback(); res.status(500).json({ error: 'Setup failed', detail: process.env.NODE_ENV === 'development' ? error.message : undefined }) } finally { connection.release() } })
app.post('/api/auth/login', async (req, res) => { const [rows] = await pool.query('SELECT * FROM users WHERE email = ? AND active = 1 LIMIT 1', [req.body.email]); const user = rows[0]; if (!user || !(await bcrypt.compare(req.body.password || '', user.password_hash))) return res.status(401).json({ error: 'Invalid email or password' }); res.json({ token: tokenFor(user), user: { id: user.id, name: user.name, email: user.email, role: user.role } }) })
app.get('/api/payment-methods', async (_req, res) => { const [rows] = await pool.query('SELECT id, name, instructions, account_label FROM payment_methods WHERE active = 1 ORDER BY sort_order, id'); res.json(rows) })
app.post('/api/payment-methods', auth, roles('admin'), async (req, res) => { const { name, instructions, accountLabel, active = true, sortOrder = 0 } = req.body; if (!name || !instructions || !accountLabel) return res.status(400).json({ error: 'Name, instructions, and account label are required' }); const [result] = await pool.query('INSERT INTO payment_methods (name, instructions, account_label, active, sort_order) VALUES (?, ?, ?, ?, ?)', [name, instructions, accountLabel, active, sortOrder]); res.status(201).json({ id: result.insertId }) })
app.patch('/api/payment-methods/:id', auth, roles('admin'), async (req, res) => { const { name, instructions, accountLabel, active, sortOrder } = req.body; await pool.query('UPDATE payment_methods SET name=COALESCE(?,name), instructions=COALESCE(?,instructions), account_label=COALESCE(?,account_label), active=COALESCE(?,active), sort_order=COALESCE(?,sort_order) WHERE id=?', [name, instructions, accountLabel, active, sortOrder, req.params.id]); res.json({ ok: true }) })

app.post('/api/orders', upload.array('artwork', 5), async (req, res) => { const { name, phone, email, service, details, urgent, deliveryAddress, deliveryZone } = req.body; if (!name || !phone || !service) return res.status(400).json({ error: 'Name, phone, and service are required' }); const publicId = publicOrderId(); const [result] = await pool.query('INSERT INTO orders (public_id, customer_name, customer_phone, customer_email, service, details, urgent, delivery_address, delivery_zone, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [publicId, name, phone, email || null, service, details || null, urgent === 'true' || urgent === true, deliveryAddress || null, deliveryZone || null, 'new']); for (const file of req.files || []) await pool.query('INSERT INTO order_files (order_id, kind, original_name, stored_name, mime_type, size_bytes) VALUES (?, "artwork", ?, ?, ?, ?)', [result.insertId, file.originalname, file.filename, file.mimetype, file.size]); await event(result.insertId, null, 'new', 'Order submitted by customer'); res.status(201).json({ id: publicId, status: 'new' }) })
app.post('/api/orders/:publicId/mark-paid', async (req, res) => { const [rows] = await pool.query('SELECT id FROM orders WHERE public_id=? LIMIT 1', [req.params.publicId]); if (!rows[0]) return res.status(404).json({ error: 'Order not found' }); await pool.query('UPDATE orders SET status="payment_verification" WHERE id=?', [rows[0].id]); await event(rows[0].id, null, 'payment_verification', 'Customer marked order as paid'); res.json({ ok: true, status: 'payment_verification' }) })
app.post('/api/orders/:publicId/payment-proof', upload.single('proof'), async (req, res) => { const [rows] = await pool.query('SELECT id FROM orders WHERE public_id=? LIMIT 1', [req.params.publicId]); if (!rows[0]) return res.status(404).json({ error: 'Order not found' }); if (!req.file) return res.status(400).json({ error: 'Payment proof is required' }); await pool.query('INSERT INTO order_files (order_id, kind, original_name, stored_name, mime_type, size_bytes) VALUES (?, "payment_proof", ?, ?, ?, ?)', [rows[0].id, req.file.originalname, req.file.filename, req.file.mimetype, req.file.size]); await pool.query('UPDATE orders SET status="payment_verification" WHERE id=?', [rows[0].id]); await event(rows[0].id, null, 'payment_verification', 'Customer uploaded payment proof'); res.json({ ok: true, status: 'payment_verification' }) })
app.get('/api/orders', auth, roles('admin', 'worker'), async (req, res) => { const [rows] = await pool.query(`SELECT o.*, u.name assigned_worker FROM orders o LEFT JOIN users u ON u.id=o.assigned_worker_id ${req.user.role === 'worker' ? 'WHERE o.assigned_worker_id = ? OR o.assigned_worker_id IS NULL' : ''} ORDER BY o.urgent DESC, o.created_at DESC`, req.user.role === 'worker' ? [req.user.id] : []); res.json(rows) })
app.patch('/api/orders/:id/status', auth, roles('admin', 'worker'), async (req, res) => { const allowed = ['quoted','awaiting_payment','payment_confirmed','design_review','approved','printing','quality_check','ready','dispatched','delivered','cancelled']; if (!allowed.includes(req.body.status)) return res.status(400).json({ error: 'Invalid status' }); const [result] = await pool.query('UPDATE orders SET status=? WHERE id=?', [req.body.status, req.params.id]); if (!result.affectedRows) return res.status(404).json({ error: 'Order not found' }); await event(req.params.id, req.user.id, req.body.status, req.body.note); res.json({ ok: true }) })
app.patch('/api/orders/:id/assign', auth, roles('admin'), async (req, res) => { await pool.query('UPDATE orders SET assigned_worker_id=? WHERE id=?', [req.body.workerId || null, req.params.id]); res.json({ ok: true }) })
app.post('/api/orders/:id/payment-proof', auth, roles('admin','worker'), upload.single('proof'), async (req, res) => { if (!req.file) return res.status(400).json({ error: 'Payment proof is required' }); await pool.query('INSERT INTO order_files (order_id, kind, original_name, stored_name, mime_type, size_bytes) VALUES (?, "payment_proof", ?, ?, ?, ?)', [req.params.id, req.file.originalname, req.file.filename, req.file.mimetype, req.file.size]); await pool.query('UPDATE orders SET status="payment_verification" WHERE id=?', [req.params.id]); await event(req.params.id, req.user.id, 'payment_verification', 'Payment proof uploaded'); res.json({ ok: true }) })
app.get('/api/files/:id', auth, roles('admin','worker'), async (req, res) => { const [rows] = await pool.query('SELECT * FROM order_files WHERE id=?', [req.params.id]); if (!rows[0]) return res.sendStatus(404); res.download(path.join(uploadDir, rows[0].stored_name), rows[0].original_name) })

app.use(express.static('dist'))
app.use((_req, res) => res.sendFile(path.resolve('dist/index.html')))
app.listen(port, () => console.log(`Maxrez API listening on ${port}`))
