import React, {useState} from 'react'
import {businessMetrics} from './business-metrics.js'
export function Analytics({orders}) {
 const [days,setDays]=useState('30'),m=businessMetrics(orders,days),money=n=>n.toLocaleString(undefined,{maximumFractionDigits:0})+' ETB'
 const metrics=[['Completed orders',m.completed],['Verified payment value',money(m.paidValue)],['Approved, unpaid quotes',money(m.approvedUnpaid)],['Unapproved estimates',money(m.estimateValue)],['Quote acceptance',m.conversion===null?'No requests':m.conversion.toFixed(0)+'%'],['Average turnaround',m.turnaround===null?'No completed timing':m.turnaround.toFixed(1)+' days'],['Repeat customers',m.repeat+' / '+m.customers],['Quote requests',m.quotes]]
 return <div className="operations-list"><label>Reporting period<select value={days} onChange={e=>setDays(e.target.value)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="all">All time</option></select></label><div className="metric-grid">{metrics.map(([title,value])=><article className="metric" key={title}><span>{title}</span><strong>{value}</strong></article>)}</div><article className="operations-panel"><h2>How these numbers are counted</h2><p>Reporting groups jobs by request date. Unapproved estimates and unpaid quotes are separate from verified payments. Verified payment value is recorded order value, not bank reconciliation. Quote acceptance counts accepted requests, not individual revisions. Repeat customers have more than one non-cancelled request across all time. Turnaround uses completion timestamps recorded by the new workflow; older jobs without one are excluded.</p></article><article className="operations-panel"><h2>Popular products</h2>{m.services.length?m.services.map(([name,count])=><div className="analytics-row" key={name}><span>{name}</span><meter min="0" max={m.active.length} value={count}/><b>{count}</b></div>):<p>No jobs in this period.</p>}</article></div>
}
export function RulesEditor({rules,setRules}) {
 const update=(key,i,field,value)=>setRules({...rules,[key]:rules[key].map((x,j)=>i===j?{...x,[field]:value}:x)});
 return <div className="rules-editor">{['sizes','materials','sides','finishes','quantityTiers','packageItems'].filter(key=>Array.isArray(rules[key])).map(key=><details key={key}><summary>{({sizes:'Sizes',materials:'Materials',sides:'Printed sides',finishes:'Finishes',quantityTiers:'Quantity discounts',packageItems:'Package contents and individual prices'})[key]}</summary>{rules[key].map((item,i)=><div className="pricing-fields" key={i}>{Object.entries(item).map(([field,value])=><label key={field}>{field}<input type={typeof value==='number'?'number':'text'} min={typeof value==='number'?0:undefined} step="any" value={value} onChange={e=>update(key,i,field,typeof value==='number'?Number(e.target.value):e.target.value)}/></label>)}<button type="button" onClick={()=>setRules({...rules,[key]:rules[key].filter((_,j)=>j!==i)})}>Remove option</button></div>)}<button type="button" onClick={()=>setRules({...rules,[key]:[...rules[key],key==='packageItems'?{id:'item-'+Date.now(),name:'New item',quantity:100,rate:0}:key==='quantityTiers'?{min:100,multiplier:1}:{value:'option-'+Date.now(),label:'New option',multiplier:1}]})}>Add option</button></details>)}</div>
}
