import React, {useState} from 'react'
export function Analytics({orders}) {
 const [days,setDays]=useState('30');const rows=orders.filter(o=>days==='all'||new Date(o.created_at)>=new Date(Date.now()-Number(days)*86400000));
 const active=rows.filter(o=>o.status!=='cancelled'),verified=active.filter(o=>o.payment_status==='verified'),sum=list=>list.reduce((n,o)=>n+Number(o.total_amount||0),0),money=n=>n.toLocaleString(undefined,{maximumFractionDigits:0})+' ETB';
 const groups=Object.entries(rows.reduce((a,o)=>({...a,[o.status]:(a[o.status]||0)+1}),{}));
 return <div className="operations-list"><label>Reporting period<select value={days} onChange={e=>setDays(e.target.value)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="all">All time</option></select></label><div className="metric-grid">{[['Orders',rows.length],['Order value',money(sum(active))],['Verified payments',money(sum(verified))],['Average order',money(active.length?sum(active)/active.length:0)]].map(([title,value])=><article className="metric" key={title}><span>{title}</span><strong>{value}</strong></article>)}</div><article className="operations-panel"><h2>Orders by status</h2><p>Based on order creation date. Cancelled orders are excluded from monetary totals. Verified payments are order totals, not a bank reconciliation.</p>{groups.length?groups.map(([status,count])=><div className="analytics-row" key={status}><span>{status.replaceAll('_',' ')}</span><meter min="0" max={rows.length} value={count}/><b>{count}</b></div>):<p>No orders in this period.</p>}</article><article className="operations-panel"><h2>Popular services</h2>{Object.entries(active.reduce((a,o)=>({...a,[o.service]:(a[o.service]||0)+1}),{})).sort((a,b)=>b[1]-a[1]).map(([name,count])=><p key={name}>{name} — {count} orders</p>)}</article></div>
}
export function RulesEditor({rules,setRules}) {
 const update=(key,i,field,value)=>setRules({...rules,[key]:rules[key].map((x,j)=>i===j?{...x,[field]:value}:x)});
 return <div className="rules-editor">{['sizes','materials','sides','finishes','quantityTiers','packageItems'].filter(key=>Array.isArray(rules[key])).map(key=><details key={key}><summary>{({sizes:'Sizes',materials:'Materials',sides:'Printed sides',finishes:'Finishes',quantityTiers:'Quantity discounts',packageItems:'Package contents and individual prices'})[key]}</summary>{rules[key].map((item,i)=><div className="pricing-fields" key={i}>{Object.entries(item).map(([field,value])=><label key={field}>{field}<input type={typeof value==='number'?'number':'text'} min={typeof value==='number'?0:undefined} step="any" value={value} onChange={e=>update(key,i,field,typeof value==='number'?Number(e.target.value):e.target.value)}/></label>)}<button type="button" onClick={()=>setRules({...rules,[key]:rules[key].filter((_,j)=>j!==i)})}>Remove option</button></div>)}<button type="button" onClick={()=>setRules({...rules,[key]:[...rules[key],key==='packageItems'?{id:'item-'+Date.now(),name:'New item',quantity:100,rate:0}:key==='quantityTiers'?{min:100,multiplier:1}:{value:'option-'+Date.now(),label:'New option',multiplier:1}]})}>Add option</button></details>)}</div>
}
