import React, {useEffect, useState} from 'react'
const money=v=>`${Number(v||0).toLocaleString()} ETB`
export default function CustomerWorkflow({token,api,go,onState}) {
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[quoteNote,setQuoteNote]=useState(''),[proofNote,setProofNote]=useState(''),[checked,setChecked]=useState(false)
 const load=async()=>{try{const next=await api(`/tracking/${token}/workflow`);setData(next);onState(next);setError('')}catch(e){setError(e.message)}}
 useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t)},[token])
 const act=async(kind,decision,version,note)=>{setBusy(true);setError('');try{await api(`/tracking/${token}/${kind}-response`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision,version,note})});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const reorder=async()=>{setBusy(true);try{const draft=await api(`/tracking/${token}/reorder`);sessionStorage.setItem('maxrez-reorder',JSON.stringify(draft));go(`/order?product=${encodeURIComponent(draft.slug)}&reorder=1`)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const q=data?.quotes?.[0],p=data?.proofs?.[0],w=data?.workflow
 useEffect(()=>setChecked(false),[p?.version])
 return <section className="customer-workflow">
  {error&&<p role="alert" className="error-text">{error}<button className="text-link" onClick={load}>Try again</button></p>}
  {!data&&!error&&<p>Loading quote and artwork…</p>}
  {data&&<><article className="flow-card"><div className="eyebrow">01 / QUOTE REVIEW</div><h2>{w?.quote_status==='requested'?'Your quote request is with our team':q?`Quote v${q.version}`:'Order pricing'}</h2><p>{q?money(q.amount):money(w?.estimate)} {q?'including delivery, if requested':'estimated — subject to review'}</p>{q?.note&&<blockquote>{q.note}</blockquote>}{q&&<span className="workflow-badge">{q.status.replaceAll('_',' ')}</span>}
   {w?.quote_status==='requested'&&<p>We’ll review your files and specifications, then confirm the price here. Please save this private link and check back for updates.</p>}
   {w?.quote_status==='sent'&&<><label>Questions or requested changes<textarea value={quoteNote} onChange={e=>setQuoteNote(e.target.value)} maxLength={4000}/></label><div className="flow-actions"><button className="primary" disabled={busy} onClick={()=>act('quote','accepted',q.version,quoteNote)}>Approve {money(q.amount)}</button><button className="outline" disabled={busy||!quoteNote.trim()} onClick={()=>act('quote','changes_requested',q.version,quoteNote)}>Request changes</button></div></>}
   {w?.quote_status==='changes_requested'&&<p>Your requested changes are with Maxrez. We’ll post a revised quote here.</p>}
   {w?.quote_status==='accepted'&&<p>Price approved. You can now submit payment using the details on this page.</p>}
   {data.quotes.length>1&&<details><summary>Previous quotes</summary>{data.quotes.slice(1).map(v=><p key={v.id}>v{v.version} · {money(v.amount)} · {v.status.replaceAll('_',' ')} {v.customer_note}</p>)}</details>}
  </article>
  <article className="flow-card"><div className="eyebrow">02 / ARTWORK APPROVAL</div><h2>{p?`Review artwork v${p.version}`:'Your artwork proof will appear here'}</h2>{p?<><a className="outline" href={`${import.meta.env.VITE_API_URL||'/api'}/tracking/${token}/proofs/${p.version}`} download>Download {p.original_name}</a><p>{p.note}</p><span className="workflow-badge">{p.status.replaceAll('_',' ')}</span>{p.status==='pending'&&<><label className="proof-confirm"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>I have checked this version’s text, layout, dimensions and colours.</label><label>Feedback<textarea value={proofNote} onChange={e=>setProofNote(e.target.value)} maxLength={4000}/></label><div className="flow-actions"><button className="primary" disabled={busy||!checked} onClick={()=>act('proof','approved',p.version,proofNote)}>Approve artwork v{p.version}</button><button className="outline" disabled={busy||!proofNote.trim()} onClick={()=>act('proof','changes_requested',p.version,proofNote)}>Request changes</button></div></>}{p.customer_note&&<blockquote>{p.customer_note}</blockquote>}<details><summary>Artwork version history</summary>{data.proofs.map(v=><p key={v.id}><a href={`${import.meta.env.VITE_API_URL||'/api'}/tracking/${token}/proofs/${v.version}`} download>Version {v.version}</a> · {v.status.replaceAll('_',' ')}{v.responded_at&&` · ${new Date(v.responded_at).toLocaleString()}`}</p>)}</details></>:<p>Our team will upload a proposed design for you to check before production.</p>}</article>
  <article className="flow-card reorder-card"><div><h2>Need another run?</h2><p>Reuse this job’s specifications and artwork, adjust the quantity, and request a fresh quote at current prices.</p></div><button className="outline" disabled={busy} onClick={reorder}>Reorder this job →</button></article></>}
 </section>
}
