import React, { useEffect, useMemo, useState } from 'react'
import ZoneEditorMap from './ZoneEditorMap.jsx'

const statuses = ['new', 'confirmed', 'paid', 'out_for_delivery', 'completed', 'cancelled']

function money(value) { return `${Math.round(Number(value || 0)).toLocaleString()} ETB` }
function sessionData() { try { return JSON.parse(localStorage.getItem('maxrez-session') || 'null') } catch { return null } }

export default function OperationsWorkspace({ api, go }) {
  const session = sessionData()
  const headers = session ? { Authorization: `Bearer ${session.token}` } : {}
  const [tab, setTab] = useState('orders')
  const [orders, setOrders] = useState([])
  const [products, setProducts] = useState([])
  const [zones, setZones] = useState([])
  const [staff, setStaff] = useState([])
  const [methods, setMethods] = useState([])
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [search, setSearch] = useState('')
  const [newStaff, setNewStaff] = useState({ name: '', email: '', password: '', role: 'worker' })
  const [newProduct, setNewProduct] = useState({ slug: '', name: '', category: 'Print services', basePrice: '', minimumQuantity: 1 })

  const load = async () => {
    if (!session) return
    setError('')
    try { setOrders(await api('/orders', { headers })) } catch (e) { setError(e.message) }
    try { setProducts(await api('/admin/products', { headers })) } catch (e) { setError(e.message) }
    if (session.user.role === 'admin') {
      try { setZones(await api('/admin/delivery-zones', { headers })) } catch (e) { setError(e.message) }
      try { setStaff(await api('/admin/staff', { headers })) } catch (e) { setError(e.message) }
      try { setMethods(await api('/payment-methods')) } catch (e) { setError(e.message) }
    }
  }
  useEffect(() => { load() }, [])

  const filteredOrders = useMemo(() => {
    const q = search.trim().toLowerCase()
    return orders.filter(o => !q || [o.public_id, o.customer_name, o.customer_phone, o.service, o.status, o.payment_status].some(v => String(v || '').toLowerCase().includes(q)))
  }, [orders, search])

  const show = (message) => { setNotice(message); setTimeout(() => setNotice(''), 3000) }
  const updateOrder = async (id, body, message) => { try { await api(`/orders/${id}/status`, { method: 'PATCH', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); show(message); load() } catch (e) { setError(e.message) } }
  const updatePayment = async (id, paymentStatus) => { try { await api(`/orders/${id}/payment`, { method: 'PATCH', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ paymentStatus }) }); show(`Payment marked ${paymentStatus}.`); load() } catch (e) { setError(e.message) } }
  const openFile = async id => { try { const response = await fetch(`/api/files/${id}`, { headers }); if (!response.ok) throw new Error('File unavailable'); const blob = await response.blob(); const url = URL.createObjectURL(blob); window.open(url, '_blank', 'noopener,noreferrer'); setTimeout(() => URL.revokeObjectURL(url), 60000) } catch (e) { setError(e.message) } }
  const saveProduct = async product => { try { const rules = typeof product.rulesText === 'string' ? JSON.parse(product.rulesText) : product.pricing_rules; await api(`/admin/products/${product.id}`, { method: 'PATCH', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ basePrice: Number(product.base_price), minimumQuantity: Number(product.minimum_quantity), pricingRules: rules, active: product.active }) }); show(`${product.name} pricing saved.`); load() } catch (e) { setError(`Pricing JSON error: ${e.message}`) } }
  const createProduct = async event => { event.preventDefault(); try { const slug = (newProduct.slug || newProduct.name).trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); if (!slug || !newProduct.name.trim() || !Number(newProduct.basePrice)) throw new Error('Add a service name and base price.'); await api('/admin/products', { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ slug, name: newProduct.name.trim(), description: `Configure ${newProduct.name.trim().toLowerCase()} and receive an instant estimate.`, category: newProduct.category.trim() || 'Print services', basePrice: Number(newProduct.basePrice), minimumQuantity: Number(newProduct.minimumQuantity) || 1 }) }); setNewProduct({ slug: '', name: '', category: 'Print services', basePrice: '', minimumQuantity: 1 }); show('New service added to the catalog.'); load() } catch (e) { setError(e.message) } }
  const saveZone = async zone => { try { await api(`/admin/delivery-zones/${zone.id}`, { method: 'PATCH', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ name: zone.name, radiusKm: Number(zone.radius_km), fee: Number(zone.fee), etaMinutes: Number(zone.eta_minutes), centerLat: zone.center_lat, centerLng: zone.center_lng, active: zone.active }) }); show(`${zone.name} saved.`); load() } catch (e) { setError(e.message) } }
  const createZone = async () => { try { await api('/admin/delivery-zones', { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ name: 'New zone', radiusKm: 5, fee: 250, etaMinutes: 60 }) }); show('Delivery zone created.'); load() } catch (e) { setError(e.message) } }
  const createStaff = async event => { event.preventDefault(); try { await api('/admin/staff', { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify(newStaff) }); setNewStaff({ name: '', email: '', password: '', role: 'worker' }); show('Account created.'); load() } catch (e) { setError(e.message) } }
  const saveMethod = async method => { try { await api(`/payment-methods/${method.id}`, { method: 'PATCH', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ accountLabel: method.account_label, instructions: method.instructions }) }); show(`${method.name} details saved.`); load() } catch (e) { setError(e.message) } }
  const uploadQr = async (id, file) => { const body = new FormData(); body.append('qr', file); try { await api(`/admin/payment-methods/${id}/qr`, { method: 'POST', headers, body }); show('Payment QR updated.'); load() } catch (e) { setError(e.message) } }

  if (!session) return <main className="workspace-empty"><h1>Sign in required</h1><button className="primary" onClick={() => go('/staff')}>Open staff login</button></main>
  const tabs = session.user.role === 'admin' ? [['orders', 'Orders'], ['payments', 'Payments'], ['pricing', 'Pricing'], ['delivery', 'Delivery zones'], ['people', 'Staff & admins'], ['payments-settings', 'Payment settings']] : [['orders', 'Orders'], ['payments', 'Payments']]

  return <main className="workspace workspace-v3">
    <header className="workspace-top"><button className="back" onClick={() => go('/')}>← Storefront</button><div className="workspace-brand"><img src="/images/maxrez-logo.png" alt="Maxrez"/></div><div className="workspace-user"><b>{session.user.name}</b><small>{session.user.role}</small><button className="back" onClick={() => { localStorage.removeItem('maxrez-session'); location.reload() }}>Sign out</button></div></header>
    <div className="workspace-layout"><aside className="workspace-nav">{tabs.map(([value, label]) => <button key={value} className={tab === value ? 'active' : ''} onClick={() => setTab(value)}>{label}{value === 'payments' && orders.filter(o => o.payment_status === 'submitted').length > 0 && <i>{orders.filter(o => o.payment_status === 'submitted').length}</i>}</button>)}</aside>
      <section className="dash"><div className="dash-head"><div><div className="eyebrow">{session.user.role.toUpperCase()} WORKSPACE</div><h1>{tabs.find(x => x[0] === tab)?.[1]}</h1></div><button className="filter" onClick={load}>↻ Refresh</button></div>{error && <div className="admin-alert error-text">{error}</div>}{notice && <div className="admin-alert success-text">{notice}</div>}
        {tab === 'orders' && <><div className="admin-toolbar"><input placeholder="Search order, customer, service, or status" value={search} onChange={e => setSearch(e.target.value)} /><span>{filteredOrders.length} orders</span></div><div className="operations-orders">{filteredOrders.length ? filteredOrders.map(order => <OrderCard key={order.id} order={order} onStatus={value => updateOrder(order.id, { status: value }, 'Order status updated.')} onPayment={value => updatePayment(order.id, value)} openFile={openFile} />) : <div className="empty-state">No orders match your search.</div>}</div></>}
        {tab === 'payments' && <div className="operations-orders">{orders.filter(o => o.payment_status === 'submitted').map(order => <OrderCard key={order.id} order={order} paymentOnly onStatus={value => updateOrder(order.id, { status: value }, 'Order status updated.')} onPayment={value => updatePayment(order.id, value)} openFile={openFile} />)}{!orders.some(o => o.payment_status === 'submitted') && <div className="empty-state"><h2>Payment queue is clear</h2><p>Submitted payment screenshots will appear here.</p></div>}</div>}
        {tab === 'pricing' && <PricingPanel products={products} setProducts={setProducts} newProduct={newProduct} setNewProduct={setNewProduct} createProduct={createProduct} saveProduct={saveProduct} canEdit={session.user.role === 'admin'} />}
        {tab === 'delivery' && <DeliveryZonesPanel zones={zones} setZones={setZones} saveZone={saveZone} createZone={createZone} />}
        {tab === 'people' && <div className="operations-list"><form className="operations-panel" onSubmit={createStaff}><div className="panel-heading"><div><h2>Create staff or admin</h2><small>Only administrators can create accounts.</small></div><button className="primary">Create account</button></div><div className="pricing-fields"><label>Name<input required value={newStaff.name} onChange={e => setNewStaff({ ...newStaff, name: e.target.value })} /></label><label>Email<input required type="email" value={newStaff.email} onChange={e => setNewStaff({ ...newStaff, email: e.target.value })} /></label><label>Temporary password<input required minLength="8" type="password" value={newStaff.password} onChange={e => setNewStaff({ ...newStaff, password: e.target.value })} /></label><label>Role<select value={newStaff.role} onChange={e => setNewStaff({ ...newStaff, role: e.target.value })}><option value="worker">Worker</option><option value="admin">Admin</option></select></label></div></form>{staff.map(member => <article className="operations-panel staff-row" key={member.id}><div><b>{member.name}</b><small>{member.email}</small></div><span>{member.role}</span><span className={member.active ? 'success-text' : 'error-text'}>{member.active ? 'Active' : 'Inactive'}</span></article>)}</div>}
        {tab === 'payments-settings' && <div className="operations-list">{methods.map((method, index) => <article className="operations-panel" key={method.id}><div className="panel-heading"><div><div className="eyebrow">PAYMENT METHOD</div><h2>{method.name}</h2><small>Customers see this account information and image while paying.</small></div><button className="primary" onClick={() => saveMethod(method)}>Save details</button></div><div className="pricing-fields"><label>Account or phone number<input value={method.account_label || ''} onChange={e => setMethods(methods.map((m, i) => i === index ? { ...m, account_label: e.target.value } : m))} /></label><label>Instructions<input value={method.instructions || ''} onChange={e => setMethods(methods.map((m, i) => i === index ? { ...m, instructions: e.target.value } : m))} /></label></div><div className="payment-image-control"><div>{method.qr_url ? <img className="payment-qr-preview" src={method.qr_url} alt={`${method.name} payment QR or instructions`} /> : <div className="payment-image-empty">No payment image attached</div>}</div><label className="file-button">Attach payment image / QR<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e => e.target.files[0] && uploadQr(method.id, e.target.files[0])} /></label></div></article>)}</div>}
      </section>
    </div>
  </main>
}

function OrderCard({ order, onStatus, onPayment, openFile, paymentOnly }) {
  const [proofs, setProofs] = useState([])
  const loadProofs = async () => { try { const session = sessionData(); const response = await fetch(`/api/orders/${order.id}/payment-proofs`, { headers: { Authorization: `Bearer ${session?.token}` } }); if (response.ok) setProofs(await response.json()) } catch {} }
  const lat = order.destination_lat || order.details?.lat
  const lng = order.destination_lng || order.details?.lng
  return <article className={`order-panel ${order.urgent ? 'urgent' : ''}`}><div className="order-panel-head"><div><span className={order.urgent ? 'urgent-pill' : 'order-type'}>{order.urgent ? 'URGENT' : 'ORDER'}</span><h2>{order.public_id}</h2><small>{order.customer_name} · {order.customer_phone}</small></div><strong>{money(order.total_amount)}</strong></div><div className="order-summary"><span>{order.service}</span><span>{order.quantity} units</span><span>{order.fulfillment_method === 'delivery' ? 'Delivery' : 'Pickup'}</span><span className={`payment-badge ${order.payment_status}`}>Payment: {order.payment_status || 'unpaid'}</span></div>{order.fulfillment_method === 'delivery' && <div className="order-location">{lat && lng ? <><iframe title={`Delivery location for ${order.public_id}`} src={`https://www.google.com/maps?q=${lat},${lng}&z=15&output=embed`} loading="lazy" /><span>Delivery pin: {lat}, {lng}</span></> : <span>Delivery location not pinned yet.</span>}</div>}<div className="order-actions">{!paymentOnly && <label>Status<select value={order.status} onChange={e => onStatus(e.target.value)}>{statuses.map(status => <option key={status} value={status}>{status.replaceAll('_', ' ')}</option>)}</select></label>}<label>Payment<select value={order.payment_status || 'unpaid'} onChange={e => onPayment(e.target.value)}>{['unpaid', 'submitted', 'verified', 'rejected'].map(status => <option key={status} value={status}>{status}</option>)}</select></label><button className="outline" onClick={loadProofs}>View payment proof</button>{order.tracking_token && <a className="outline" href={`/track/${order.tracking_token}`} target="_blank" rel="noreferrer">Tracking link</a>}</div>{proofs.map(proof => <button className="proof-link" key={proof.id} onClick={() => openFile(proof.id)}>Open {proof.original_name}</button>)}</article>
}

function DeliveryZonesPanel({ zones, setZones, saveZone, createZone }) {
  const update = (index, key, value) => setZones(zones.map((zone, i) => i === index ? { ...zone, [key]: value } : zone))
  return <div className="operations-list"><article className="operations-panel delivery-map-panel"><div className="panel-heading"><div><div className="eyebrow">DELIVERY COVERAGE</div><h2>Place and resize your zones</h2><p>Drag each numbered pin to the area you serve. Drag its small handle to make the radius bigger or smaller, then save the zone below.</p><small className="map-facility-note">Map center: Maxrez facility, Gabon Street Woreda 02, House no. 359</small></div><button className="primary" onClick={createZone}>+ Add zone</button></div><ZoneEditorMap zones={zones} setZones={setZones} /></article>{zones.map((zone, index) => <article className="operations-panel" key={zone.id}><div className="panel-heading"><div><div className="eyebrow">ZONE {index + 1}</div><h2>{zone.name}</h2><small>Set the exact delivery price customers will pay for this radius.</small></div><button className="primary" onClick={() => saveZone(zone)}>Save zone</button></div><div className="pricing-fields"><label>Zone name<input value={zone.name} onChange={e => update(index, 'name', e.target.value)} /></label><label>Radius (km)<input type="number" min="0.1" step="0.1" value={zone.radius_km} onChange={e => update(index, 'radius_km', e.target.value)} /></label><label>Delivery fee (ETB)<input type="number" min="0" step="1" value={zone.fee} onChange={e => update(index, 'fee', e.target.value)} /></label><label>ETA (minutes)<input type="number" min="1" step="1" value={zone.eta_minutes} onChange={e => update(index, 'eta_minutes', e.target.value)} /></label><label className="zone-active-field"><input type="checkbox" checked={zone.active !== 0 && zone.active !== false} onChange={e => update(index, 'active', e.target.checked)} /> Active for customer quotes</label><label>Center latitude<input type="number" step="0.000001" value={zone.center_lat ?? ''} onChange={e => update(index, 'center_lat', e.target.value)} placeholder="Drag the map pin" /></label><label>Center longitude<input type="number" step="0.000001" value={zone.center_lng ?? ''} onChange={e => update(index, 'center_lng', e.target.value)} placeholder="Drag the map pin" /></label></div></article>)}</div>
}

function LegacyDeliveryZonesPanel({ zones, setZones, saveZone, createZone }) {
  const maxRadius = Math.max(1, ...zones.map(zone => Number(zone.radius_km) || 0))
  const update = (index, key, value) => setZones(zones.map((zone, i) => i === index ? { ...zone, [key]: value } : zone))
  return <div className="operations-list"><article className="operations-panel delivery-map-panel"><div className="panel-heading"><div><div className="eyebrow">DELIVERY COVERAGE</div><h2>Custom delivery radiuses</h2><p>Every circle is measured from the Maxrez facility. Set the radius, delivery price, and ETA for each zone.</p><small className="map-facility-note">Facility: Gabon Street Woreda 02, House no. 359</small></div><button className="primary" onClick={createZone}>+ Add radius</button></div><div className="zone-map-layout"><div className="zone-map-preview"><iframe title="Maxrez delivery coverage map" src="https://www.google.com/maps?q=Gabon%20Street%20Woreda%2002%20Addis%20Ababa&z=13&output=embed" loading="lazy" /><div className="zone-map-circles" aria-hidden="true"><span className="zone-map-center">MAXREZ</span>{zones.slice().sort((a, b) => Number(b.radius_km) - Number(a.radius_km)).map((zone, index) => <i key={zone.id || index} style={{ width: `${Math.max(28, Number(zone.radius_km) / maxRadius * 92)}%`, height: `${Math.max(28, Number(zone.radius_km) / maxRadius * 92)}%`, borderColor: `hsl(${index * 54 + 4} 70% 48% / .72)` }} />)}</div></div><div className="zone-map-legend"><strong>How pricing works</strong><p>Customer pins are checked against these radiuses. The smallest matching radius supplies the delivery fee.</p>{zones.length ? zones.slice().sort((a, b) => Number(a.radius_km) - Number(b.radius_km)).map((zone, index) => <div className="zone-legend-row" key={zone.id || index}><i style={{ background: `hsl(${index * 54 + 4} 70% 48%)` }} /><span><b>{zone.name}</b><small>Up to {zone.radius_km} km · {money(zone.fee)} · {zone.eta_minutes} min</small></span></div>) : <span className="muted">Add your first delivery radius.</span>}</div></div></article>{zones.map((zone, index) => <article className="operations-panel" key={zone.id}><div className="panel-heading"><div><div className="eyebrow">ZONE {index + 1}</div><h2>{zone.name}</h2><small>Changes apply to future delivery quotes.</small></div><button className="primary" onClick={() => saveZone(zone)}>Save zone</button></div><div className="pricing-fields"><label>Zone name<input value={zone.name} onChange={e => update(index, 'name', e.target.value)} /></label><label>Radius (km)<input type="number" min="0.1" step="0.1" value={zone.radius_km} onChange={e => update(index, 'radius_km', e.target.value)} /></label><label>Delivery fee (ETB)<input type="number" min="0" value={zone.fee} onChange={e => update(index, 'fee', e.target.value)} /></label><label>ETA (minutes)<input type="number" min="1" value={zone.eta_minutes} onChange={e => update(index, 'eta_minutes', e.target.value)} /></label><label className="zone-active-field"><input type="checkbox" checked={zone.active !== 0 && zone.active !== false} onChange={e => update(index, 'active', e.target.checked)} /> Active for customer quotes</label></div></article>)}</div>
}

function PricingPanel({ products, setProducts, newProduct, setNewProduct, createProduct, saveProduct, canEdit }) {
  const updateProduct = (index, key, value) => setProducts(products.map((product, i) => i === index ? { ...product, [key]: value } : product))
  return <div className="operations-list"><form className="operations-panel create-service-panel" onSubmit={createProduct}><div className="panel-heading"><div><div className="eyebrow">SERVICE CATALOG</div><h2>Add a new service</h2><p>Create another orderable service; it will immediately use the standard pricing options.</p></div><button className="primary" disabled={!canEdit}>Add service</button></div><div className="pricing-fields"><label>Service name<input required value={newProduct.name} onChange={e => setNewProduct({ ...newProduct, name: e.target.value })} placeholder="e.g. Menu printing" /></label><label>Category<input value={newProduct.category} onChange={e => setNewProduct({ ...newProduct, category: e.target.value })} placeholder="e.g. Restaurant print" /></label><label>Base price per unit (ETB)<input required type="number" min="0.01" step="0.01" value={newProduct.basePrice} onChange={e => setNewProduct({ ...newProduct, basePrice: e.target.value })} /></label><label>Minimum quantity<input required type="number" min="1" value={newProduct.minimumQuantity} onChange={e => setNewProduct({ ...newProduct, minimumQuantity: e.target.value })} /></label></div></form>{products.map((product, index) => <ProductPricingCard key={product.id} product={product} index={index} updateProduct={updateProduct} setProducts={setProducts} saveProduct={saveProduct} canEdit={canEdit} />)}</div>
}

function ProductPricingCard({ product, index, updateProduct, setProducts, saveProduct, canEdit }) {
  let rules = product.pricing_rules || {}
  if (typeof product.rulesText === 'string') { try { rules = JSON.parse(product.rulesText) } catch {} }
  const multiplier = (key, value, fallback = 1) => Number(rules[key]?.find(item => item.value === value)?.multiplier ?? fallback)
  const setRules = updated => setProducts(products => products.map(item => item.id === product.id ? { ...item, pricing_rules: updated, rulesText: JSON.stringify(updated, null, 2) } : item))
  const setMultiplier = (key, value, next) => setRules({ ...rules, [key]: (rules[key] || []).map(item => item.value === value ? { ...item, multiplier: Number(next) } : item) })
  return <article className="operations-panel"><div className="panel-heading"><div><h2>{product.name}</h2><small>{product.category}</small></div><button className="primary" disabled={!canEdit} onClick={() => saveProduct(product)}>Save pricing</button></div><div className="pricing-fields"><label>Base price per unit<input type="number" min="0" step="0.01" value={product.base_price} onChange={e => updateProduct(index, 'base_price', e.target.value)} /></label><label>Minimum quantity<input type="number" min="1" value={product.minimum_quantity} onChange={e => updateProduct(index, 'minimum_quantity', e.target.value)} /></label><label>A4 multiplier<input type="number" min="0" step="0.01" value={multiplier('sizes', 'A4')} onChange={e => setMultiplier('sizes', 'A4', e.target.value)} /></label><label>Double-sided multiplier<input type="number" min="0" step="0.01" value={multiplier('sides', 'double')} onChange={e => setMultiplier('sides', 'double', e.target.value)} /></label><label>Design fee (ETB)<input type="number" min="0" value={Number(rules.designFee || 0)} onChange={e => setRules({ ...rules, designFee: Number(e.target.value) })} /></label><label>Urgent multiplier<input type="number" min="1" step="0.01" value={Number(rules.urgentMultiplier || 1)} onChange={e => setRules({ ...rules, urgentMultiplier: Number(e.target.value) })} /></label></div><details className="advanced-rules"><summary>Advanced pricing options</summary><p>Edit sizes, materials, finishing, and quantity tiers only if needed.</p><textarea value={product.rulesText ?? JSON.stringify(product.pricing_rules, null, 2)} onChange={e => updateProduct(index, 'rulesText', e.target.value)} spellCheck="false" /></details></article>
}
