import React, { useEffect, useMemo, useState } from 'react'

const statuses = ['new', 'confirmed', 'paid', 'out_for_delivery', 'completed', 'cancelled']

function money(value) { return `${Math.round(Number(value || 0)).toLocaleString()} ETB` }
function sessionData() { try { return JSON.parse(localStorage.getItem('maxrez-session') || 'null') } catch { return null } }

export default function OperationsWorkspace({ api, go }) {
  const session = sessionData()
  const headers = session ? { Authorization: `Bearer ${session.token}` } : {}
  const [tab, setTab] = useState('orders')
  const [orders, setOrders] = useState([])
  const [products, setProducts] = useState([])
  const [zones, setZones] = useState([])
  const [staff, setStaff] = useState([])
  const [methods, setMethods] = useState([])
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [search, setSearch] = useState('')
  const [newStaff, setNewStaff] = useState({ name: '', email: '', password: '', role: 'worker' })

  const load = async () => {
    if (!session) return
    setError('')
    try { setOrders(await api('/orders', { headers })) } catch (e) { setError(e.message) }
    try { setProducts(await api('/admin/products', { headers })) } catch (e) { setError(e.message) }
    if (session.user.role === 'admin') {
      try { setZones(await api('/admin/delivery-zones', { headers })) } catch (e) { setError(e.message) }
      try { setStaff(await api('/admin/staff', { headers })) } catch (e) { setError(e.message) }
      try { setMethods(await api('/payment-methods')) } catch (e) { setError(e.message) }
    }
  }
  useEffect(() => { load() }, [])

  const filteredOrders = useMemo(() => {
    const q = search.trim().toLowerCase()
    return orders.filter(o => !q || [o.public_id, o.customer_name, o.customer_phone, o.service, o.status, o.payment_status].some(v => String(v || '').toLowerCase().includes(q)))
  }, [orders, search])

  const show = (message) => { setNotice(message); setTimeout(() => setNotice(''), 3000) }
  const updateOrder = async (id, body, message) => { try { await api(`/orders/${id}/status`, { method: 'PATCH', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); show(message); load() } catch (e) { setError(e.message) } }
  const assignOrder = async (id, workerId) => { try { await api(`/orders/${id}/assign`, { method: 'PATCH', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ workerId: workerId ? Number(workerId) : null }) }); show(workerId ? 'Order assigned.' : 'Order unassigned.'); load() } catch (e) { setError(e.message) } }
  const updatePayment = async (id, paymentStatus) => { try { await api(`/orders/${id}/payment`, { method: 'PATCH', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ paymentStatus }) }); show(`Payment marked ${paymentStatus}.`); load() } catch (e) { setError(e.message) } }
  const openFile = async id => { try { const response = await fetch(`/api/files/${id}`, { headers }); if (!response.ok) throw new Error('File unavailable'); const blob = await response.blob(); const url = URL.createObjectURL(blob); window.open(url, '_blank', 'noopener,noreferrer'); setTimeout(() => URL.revokeObjectURL(url), 60000) } catch (e) { setError(e.message) } }
  const saveProduct = async product => { try { const rules = typeof product.rulesText === 'string' ? JSON.parse(product.rulesText) : product.pricing_rules; await api(`/admin/products/${product.id}`, { method: 'PATCH', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ basePrice: Number(product.base_price), minimumQuantity: Number(product.minimum_quantity), pricingRules: rules, active: product.active }) }); show(`${product.name} pricing saved.`); load() } catch (e) { setError(`Pricing JSON error: ${e.message}`) } }
  const saveZone = async zone => { try { await api(`/admin/delivery-zones/${zone.id}`, { method: 'PATCH', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ name: zone.name, radiusKm: Number(zone.radius_km), fee: Number(zone.fee), etaMinutes: Number(zone.eta_minutes), centerLat: zone.center_lat, centerLng: zone.center_lng, active: zone.active }) }); show(`${zone.name} saved.`); load() } catch (e) { setError(e.message) } }
  const createZone = async () => { try { await api('/admin/delivery-zones', { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ name: 'New zone', radiusKm: 5, fee: 250, etaMinutes: 60 }) }); show('Delivery zone created.'); load() } catch (e) { setError(e.message) } }
  const createStaff = async event => { event.preventDefault(); try { await api('/admin/staff', { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify(newStaff) }); setNewStaff({ name: '', email: '', password: '', role: 'worker' }); show('Account created.'); load() } catch (e) { setError(e.message) } }
  const saveMethod = async method => { try { await api(`/payment-methods/${method.id}`, { method: 'PATCH', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ accountLabel: method.account_label, instructions: method.instructions }) }); show(`${method.name} details saved.`); load() } catch (e) { setError(e.message) } }
  const uploadQr = async (id, file) => { const body = new FormData(); body.append('qr', file); try { await api(`/admin/payment-methods/${id}/qr`, { method: 'POST', headers, body }); show('Payment QR updated.'); load() } catch (e) { setError(e.message) } }

  if (!session) return <main className="workspace-empty"><h1>Sign in required</h1><button className="primary" onClick={() => go('/staff')}>Open staff login</button></main>
  const tabs = session.user.role === 'admin' ? [['orders', 'Orders'], ['payments', 'Payments'], ['pricing', 'Pricing'], ['delivery', 'Delivery zones'], ['people', 'Staff & admins'], ['payments-settings', 'Payment settings']] : [['orders', 'Orders'], ['payments', 'Payments']]

  return <main className="workspace workspace-v3">
    <header className="workspace-top"><button className="back" onClick={() => go('/')}>← Storefront</button><div className="workspace-brand"><img src="/images/maxrez-logo.png" alt="Maxrez"/><span>Operations</span></div><div className="workspace-user"><b>{session.user.name}</b><small>{session.user.role}</small><button className="back" onClick={() => { localStorage.removeItem('maxrez-session'); location.reload() }}>Sign out</button></div></header>
    <div className="workspace-layout"><aside className="workspace-nav">{tabs.map(([value, label]) => <button key={value} className={tab === value ? 'active' : ''} onClick={() => setTab(value)}>{label}{value === 'payments' && orders.filter(o => o.payment_status === 'submitted').length > 0 && <i>{orders.filter(o => o.payment_status === 'submitted').length}</i>}</button>)}</aside>
      <section className="dash"><div className="dash-head"><div><div className="eyebrow">{session.user.role.toUpperCase()} WORKSPACE</div><h1>{tabs.find(x => x[0] === tab)?.[1]}</h1></div><button className="filter" onClick={load}>↻ Refresh</button></div>{error && <div className="admin-alert error-text">{error}</div>}{notice && <div className="admin-alert success-text">{notice}</div>}
        {tab === 'orders' && <><div className="admin-toolbar"><input placeholder="Search order, customer, service, or status" value={search} onChange={e => setSearch(e.target.value)} /><span>{filteredOrders.length} orders</span></div><div className="operations-orders">{filteredOrders.length ? filteredOrders.map(order => <OrderCard key={order.id} order={order} staff={staff} onAssign={assignOrder} onStatus={value => updateOrder(order.id, { status: value }, 'Order status updated.')} onPayment={value => updatePayment(order.id, value)} openFile={openFile} />) : <div className="empty-state">No orders match your search.</div>}</div></>}
        {tab === 'payments' && <div className="operations-orders">{orders.filter(o => o.payment_status === 'submitted').map(order => <OrderCard key={order.id} order={order} staff={staff} onAssign={assignOrder} paymentOnly onStatus={value => updateOrder(order.id, { status: value }, 'Order status updated.')} onPayment={value => updatePayment(order.id, value)} openFile={openFile} />)}{!orders.some(o => o.payment_status === 'submitted') && <div className="empty-state"><h2>Payment queue is clear</h2><p>Submitted payment screenshots will appear here.</p></div>}</div>}
        {tab === 'pricing' && <div className="operations-list">{products.map((product, index) => <article className="operations-panel" key={product.id}><div className="panel-heading"><div><h2>{product.name}</h2><small>{product.category}</small></div><button className="primary" disabled={session.user.role !== 'admin'} onClick={() => saveProduct(product)}>Save pricing</button></div><div className="pricing-fields"><label>Base price per unit<input type="number" value={product.base_price} onChange={e => setProducts(products.map((p, i) => i === index ? { ...p, base_price: e.target.value } : p))} /></label><label>Minimum quantity<input type="number" value={product.minimum_quantity} onChange={e => setProducts(products.map((p, i) => i === index ? { ...p, minimum_quantity: e.target.value } : p))} /></label></div><label className="rules-editor">Sizes, materials, sides, finishes, quantity tiers, design fee, urgent multiplier<textarea value={product.rulesText ?? JSON.stringify(product.pricing_rules, null, 2)} onChange={e => setProducts(products.map((p, i) => i === index ? { ...p, rulesText: e.target.value } : p))} spellCheck="false" /></label></article>)}</div>}
        {tab === 'delivery' && <DeliveryZonesPanel zones={zones} setZones={setZones} saveZone={saveZone} createZone={createZone} />}
        {tab === 'people' && <div className="operations-list"><form className="operations-panel" onSubmit={createStaff}><div className="panel-heading"><div><h2>Create staff or admin</h2><small>Only administrators can create accounts.</small></div><button className="primary">Create account</button></div><div className="pricing-fields"><label>Name<input required value={newStaff.name} onChange={e => setNewStaff({ ...newStaff, name: e.target.value })} /></label><label>Email<input required type="email" value={newStaff.email} onChange={e => setNewStaff({ ...newStaff, email: e.target.value })} /></label><label>Temporary password<input required minLength="8" type="password" value={newStaff.password} onChange={e => setNewStaff({ ...newStaff, password: e.target.value })} /></label><label>Role<select value={newStaff.role} onChange={e => setNewStaff({ ...newStaff, role: e.target.value })}><option value="worker">Worker</option><option value="admin">Admin</option></select></label></div></form>{staff.map(member => <article className="operations-panel staff-row" key={member.id}><div><b>{member.name}</b><small>{member.email}</small></div><span>{member.role}</span><span className={member.active ? 'success-text' : 'error-text'}>{member.active ? 'Active' : 'Inactive'}</span></article>)}</div>}
        {tab === 'payments-settings' && <div className="operations-list">{methods.map((method, index) => <article className="operations-panel" key={method.id}><div className="panel-heading"><div><h2>{method.name}</h2><small>Customers see these details after an order is confirmed.</small></div><button className="primary" onClick={() => saveMethod(method)}>Save details</button></div><div className="pricing-fields"><label>Account or phone number<input value={method.account_label || ''} onChange={e => setMethods(methods.map((m, i) => i === index ? { ...m, account_label: e.target.value } : m))} /></label><label>Instructions<input value={method.instructions || ''} onChange={e => setMethods(methods.map((m, i) => i === index ? { ...m, instructions: e.target.value } : m))} /></label></div>{method.qr_url && <img className="payment-qr-preview" src={method.qr_url} alt={`${method.name} QR code`} />}<label className="file-button">Replace QR image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e => e.target.files[0] && uploadQr(method.id, e.target.files[0])} /></label></article>)}</div>}
      </section>
    </div>
  </main>
}

function OrderCard({ order, staff, onAssign, onStatus, onPayment, openFile, paymentOnly }) {
  const [proofs, setProofs] = useState([])
  const loadProofs = async () => { try { const session = sessionData(); const response = await fetch(`/api/orders/${order.id}/payment-proofs`, { headers: { Authorization: `Bearer ${session?.token}` } }); if (response.ok) setProofs(await response.json()) } catch {} }
  const lat = order.destination_lat || order.details?.lat
  const lng = order.destination_lng || order.details?.lng
  return <article className={`order-panel ${order.urgent ? 'urgent' : ''}`}><div className="order-panel-head"><div><span className={order.urgent ? 'urgent-pill' : 'order-type'}>{order.urgent ? 'URGENT' : 'ORDER'}</span><h2>{order.public_id}</h2><small>{order.customer_name} · {order.customer_phone}</small></div><strong>{money(order.total_amount)}</strong></div><div className="order-summary"><span>{order.service}</span><span>{order.quantity} units</span><span>{order.fulfillment_method === 'delivery' ? 'Delivery' : 'Pickup'}</span><span className={`payment-badge ${order.payment_status}`}>Payment: {order.payment_status || 'unpaid'}</span></div>{order.fulfillment_method === 'delivery' && <div className="order-location">{lat && lng ? <><iframe title={`Delivery location for ${order.public_id}`} src={`https://www.google.com/maps?q=${lat},${lng}&z=15&output=embed`} loading="lazy" /><span>Delivery pin: {lat}, {lng}</span></> : <span>Delivery location not pinned yet.</span>}</div>}<div className="order-actions">{!paymentOnly && <label>Status<select value={order.status} onChange={e => onStatus(e.target.value)}>{statuses.map(status => <option key={status} value={status}>{status.replaceAll('_', ' ')}</option>)}</select></label>}{staff?.length > 0 && <label>Worker<select value={order.assigned_worker_id || ''} onChange={e => onAssign(order.id, e.target.value)}><option value="">Unassigned</option>{staff.filter(member => member.role === 'worker' && member.active).map(member => <option value={member.id} key={member.id}>{member.name}</option>)}</select></label>}<label>Payment<select value={order.payment_status || 'unpaid'} onChange={e => onPayment(e.target.value)}>{['unpaid', 'submitted', 'verified', 'rejected'].map(status => <option key={status} value={status}>{status}</option>)}</select></label><button className="outline" onClick={loadProofs}>View payment proof</button>{order.tracking_token && <a className="outline" href={`/track/${order.tracking_token}`} target="_blank" rel="noreferrer">Tracking link</a>}</div>{proofs.map(proof => <button className="proof-link" key={proof.id} onClick={() => openFile(proof.id)}>Open {proof.original_name}</button>)}</article>
}

function DeliveryZonesPanel({ zones, setZones, saveZone, createZone }) {
  const maxRadius = Math.max(1, ...zones.map(zone => Number(zone.radius_km) || 0))
  const update = (index, key, value) => setZones(zones.map((zone, i) => i === index ? { ...zone, [key]: value } : zone))
  return <div className="operations-list"><article className="operations-panel delivery-map-panel"><div className="panel-heading"><div><div className="eyebrow">DELIVERY COVERAGE</div><h2>Custom delivery radiuses</h2><p>Every circle is measured from the Maxrez facility. Set the radius, delivery price, and ETA for each zone.</p></div><button className="primary" onClick={createZone}>+ Add radius</button></div><div className="zone-map-layout"><div className="zone-map-preview"><iframe title="Maxrez delivery coverage map" src="https://www.google.com/maps?q=Gabon%20Street%20Woreda%2002%20Addis%20Ababa&z=13&output=embed" loading="lazy" /><div className="zone-map-circles" aria-hidden="true"><span className="zone-map-center">MAXREZ</span>{zones.slice().sort((a, b) => Number(b.radius_km) - Number(a.radius_km)).map((zone, index) => <i key={zone.id || index} style={{ width: `${Math.max(28, Number(zone.radius_km) / maxRadius * 92)}%`, height: `${Math.max(28, Number(zone.radius_km) / maxRadius * 92)}%`, borderColor: `hsl(${index * 54 + 4} 70% 48% / .72)` }} />)}</div></div><div className="zone-map-legend"><strong>How pricing works</strong><p>Customer pins are checked against these radiuses. The first matching radius supplies the delivery fee.</p>{zones.length ? zones.slice().sort((a, b) => Number(a.radius_km) - Number(b.radius_km)).map((zone, index) => <div className="zone-legend-row" key={zone.id || index}><i style={{ background: `hsl(${index * 54 + 4} 70% 48%)` }} /><span><b>{zone.name}</b><small>Up to {zone.radius_km} km · {money(zone.fee)} · {zone.eta_minutes} min</small></span></div>) : <span className="muted">Add your first delivery radius.</span>}</div></div></article>{zones.map((zone, index) => <article className="operations-panel" key={zone.id}><div className="panel-heading"><div><div className="eyebrow">ZONE {index + 1}</div><h2>{zone.name}</h2><small>Changes apply to future delivery quotes.</small></div><button className="primary" onClick={() => saveZone(zone)}>Save zone</button></div><div className="pricing-fields"><label>Zone name<input value={zone.name} onChange={e => update(index, 'name', e.target.value)} /></label><label>Radius (km)<input type="number" min="0.1" step="0.1" value={zone.radius_km} onChange={e => update(index, 'radius_km', e.target.value)} /></label><label>Delivery fee (ETB)<input type="number" min="0" value={zone.fee} onChange={e => update(index, 'fee', e.target.value)} /></label><label>ETA (minutes)<input type="number" min="1" value={zone.eta_minutes} onChange={e => update(index, 'eta_minutes', e.target.value)} /></label></div></article>)}</div>
}
