import React,{useEffect,useState} from 'react'
const samples=[
 {id:'label',kind:'project',title:'Label design',category:'Labels',description:'A coordinated label system across product sizes and colourways.',image_url:'/images/portfolio/soap-after.png.webp'},
 {id:'restaurant',kind:'project',title:'Restaurant identity',category:'Stationery',description:'Menus and printed brand materials presented as a coordinated collection.',image_url:'/images/portfolio/restaurant-after.png.webp'},
 {id:'book',kind:'project',title:'Publishing design',category:'Books',description:'Cover design, page layout and finishing brought together.',image_url:'/images/portfolio/book-after.png.webp'},
 {id:'afro',kind:'project',title:'Agricultural brand artwork',category:'Marketing',description:'An existing portfolio design combining bilingual copy and agricultural imagery.',image_url:'/images/work-1.png'},
 {id:'rainbow',kind:'project',title:'Confectionery product range',category:'Packaging',description:'An existing portfolio layout presenting a colourful confectionery range.',image_url:'/images/work-6.jpg'}
]
export function Stories({api,compact=false,go}) {
 const [rows,setRows]=useState(samples),[category,setCategory]=useState('All')
 useEffect(()=>{api('/stories').then(data=>setRows([...data,...samples])).catch(()=>{})},[])
 const projects=rows.filter(r=>r.kind!=='review'),reviews=rows.filter(r=>r.kind==='review')
 const filtered=category==='All'?projects:projects.filter(r=>r.category===category)
 return <section className="story-section"><div className="section-head"><div><div className="eyebrow">PRINT IN EVERY FORM</div><h2>{compact?'Ideas made tangible.':'Explore the collection.'}</h2></div><p>Browse design examples and published projects. Tell us which direction suits your next print job.</p></div>{!compact&&<div className="story-filters" aria-label="Portfolio categories">{['All',...new Set(projects.map(r=>r.category))].map(c=><button className={category===c?'active':''} aria-pressed={category===c} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div>}<div className="story-grid">{(compact?projects.slice(0,3):filtered).map(r=><article key={r.id}><img src={r.image_url} alt={r.title} loading="lazy" decoding="async"/><div><span className="eyebrow">{r.category}</span><h3>{r.title}</h3><p>{r.description}</p></div></article>)}</div>{compact&&<button className="outline" onClick={()=>go('/work')}>Explore all work →</button>}{reviews.length>0&&<div className="review-grid">{reviews.map(r=><figure key={r.id}><blockquote>{r.description}</blockquote><figcaption>{r.customer_name} · {r.title}</figcaption></figure>)}</div>}</section>
}
export function ContentEditor({api,headers}) {
 const blank={kind:'project',title:'',category:'Packaging',description:'',image_url:'',customer_name:'',consent:false,published:false}
 const [rows,setRows]=useState([]),[form,setForm]=useState(blank),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const load=()=>api('/admin/stories',{headers}).then(setRows).catch(e=>setMessage(e.message))
 useEffect(()=>{load()},[])
 const save=async e=>{e.preventDefault();setBusy(true);try{await api('/admin/stories',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(form)});setMessage('Content saved.');setForm(blank);await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 const upload=async f=>{if(!f)return;setBusy(true);try{const body=new FormData();body.append('image',f);const data=await api('/admin/story-image',{method:'POST',headers,body,onUploadProgress:()=>{}});setForm(s=>({...s,image_url:data.url}));setMessage('Photo ready to publish.')}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <div className="operations-list"><form className="operations-panel workflow-form" onSubmit={save}><h2>{form.id?'Edit content':'Add a project, studio photo or review'}</h2><p>Use your own photographs and approved customer words. Drafts stay private until published.</p><label>Type<select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="project">Project</option><option value="studio">Studio / team</option><option value="review">Customer review</option></select></label>{['title','category','description',...(form.kind==='review'?['customer_name']:[])].map(key=><label key={key}>{key.replaceAll('_',' ')}{key==='description'?<textarea required value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input required value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}{form.kind!=='review'&&<><label>Upload photo (JPG, PNG or WebP, up to 10 MB)<input type="file" accept=".jpg,.jpeg,.png,.webp" onChange={e=>upload(e.target.files[0])}/></label><label>Or use an existing image path<input placeholder="/images/work-1.png" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/></label>{form.image_url&&<img className="editor-preview" src={form.image_url} alt="Content preview"/>}</>}{form.kind==='review'&&<label className="proof-confirm"><input type="checkbox" checked={Boolean(form.consent)} onChange={e=>setForm({...form,consent:e.target.checked})}/>Customer has given permission to publish this review</label>}<label className="proof-confirm"><input type="checkbox" checked={Boolean(form.published)} onChange={e=>setForm({...form,published:e.target.checked})}/>Publish on the website</label><div className="flow-actions"><button className="primary" disabled={busy}>Save content</button><button type="button" className="outline" onClick={()=>setForm(blank)}>New entry</button></div>{message&&<p role="status">{message}</p>}</form>{rows.map(r=><article className="operations-panel" key={r.id}><h3>{r.title}</h3><p>{r.kind} · {r.published?'Published':'Draft'}</p><button className="outline" onClick={()=>setForm(r)}>Edit / unpublish</button></article>)}</div>
}
