import React,{useEffect,useState} from 'react'
const money=v=>`${Number(v||0).toLocaleString()} ETB`
export function DailyQueue({rows,drops,onTab,isAdmin=true}) {
 const active=rows.filter(o=>!['completed','cancelled'].includes(o.status)),today=new Date().toLocaleDateString()
 const due=active.filter(o=>o.promised_at&&new Date(o.promised_at).toLocaleDateString()===today)
 return <div className="operations-list"><p className="queue-intro">Start with what needs your attention today.</p><div className="queue-grid">{[['New files',drops.filter(d=>d.status==='new').length,'file-drops'],['Quotes to confirm',active.filter(o=>['requested','changes_requested'].includes(o.quote_status)).length,'quotes'],['Awaiting approval',active.filter(o=>o.quote_status==='sent'||o.proof_status==='pending').length,'proofs'],['Due today',due.length,'orders']].map(([title,n,tab])=><button className="queue-tile" key={title} onClick={()=>onTab(!isAdmin&&tab==='quotes'?'orders':tab)}><span>{title}</span><strong>{n}</strong><small>Open queue ↗</small></button>)}</div><article className="operations-panel"><h2>Today’s jobs</h2>{due.length?due.map(o=><div className="queue-job" key={o.id}><b>{o.public_id}</b><span>{o.customer_name} · {o.service}</span><span>{o.status.replaceAll('_',' ')}</span></div>):<p>No open jobs are due today.</p>}</article><article className="operations-panel"><h2>Production checks</h2><p>{active.filter(o=>o.quote_status==='accepted'&&o.payment_status==='verified'&&o.proof_status==='approved').length} jobs have an approved price, verified payment and approved artwork.</p><button className="outline" onClick={()=>onTab('orders')}>Open orders</button></article></div>
}
export function WorkflowPanel({rows,api,headers,mode,onRefresh,isAdmin}) {
 const [filter,setFilter]=useState('active')
 const list=rows.filter(o=>mode==='quotes'?o.quote_status:o.quote_status==='accepted'||o.proof_version).filter(o=>filter==='all'||!['completed','cancelled'].includes(o.status))
 return <div className="operations-list"><div className="admin-toolbar"><p>{mode==='quotes'?'Review estimates, adjust the complete price and send a quote for customer approval.':'Upload each new artwork version and follow customer feedback.'}</p><select aria-label="Job filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Open jobs</option><option value="all">All jobs</option></select></div>{list.map(o=><WorkflowJob key={o.id} order={o} api={api} headers={headers} mode={mode} onRefresh={onRefresh} isAdmin={isAdmin}/>)}{!list.length&&<div className="empty-state">This queue is clear.</div>}</div>
}
function WorkflowJob({order:o,api,headers,mode,onRefresh,isAdmin}) {
 const [data,setData]=useState(null),[amount,setAmount]=useState(o.total_amount),[note,setNote]=useState(''),[file,setFile]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[due,setDue]=useState('')
 const load=async()=>{try{setData(await api(`/admin/orders/${o.id}/workflow`,{headers}))}catch(e){setError(e.message)}}
 const send=async e=>{e.preventDefault();setBusy(true);setError('');try{if(mode==='quotes')await api(`/admin/orders/${o.id}/quote`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({amount,note,promisedAt:due?new Date(due).toISOString():null})});else{if(!file)throw new Error('Choose the proposed artwork.');const body=new FormData();body.append('proof',file);body.append('note',note);await api(`/admin/orders/${o.id}/proofs`,{method:'POST',headers,body,onUploadProgress:setProgress})}setNote('');setFile(null);await load();await onRefresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const download=async f=>{try{const r=await fetch(`${import.meta.env.VITE_API_URL||'/api'}/files/${f.id}`,{headers});if(!r.ok)throw new Error('File unavailable');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=f.original_name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}catch(e){setError(e.message)}}
 let details=o.details;try{if(typeof details==='string')details=JSON.parse(details)}catch{details={}}
 return <article className="operations-panel"><div className="panel-heading"><div><div className="eyebrow">{o.public_id}</div><h2>{o.customer_name} · {o.service}</h2><p>{o.customer_phone} · {o.customer_email}</p></div><span className="workflow-badge">{(mode==='quotes'?o.quote_status:o.proof_status||'awaiting artwork').replaceAll('_',' ')}</span></div><p>Original estimate: {money(o.estimate)} · Current price: {money(o.total_amount)} · {o.fulfillment_method}</p><details onToggle={e=>e.currentTarget.open&&!data&&load()}><summary>Specifications, files and history</summary><dl className="spec-list">{Object.entries(details||{}).filter(([k])=>!['reorderToken','lat','lng'].includes(k)).map(([k,v])=><React.Fragment key={k}><dt>{k.replace(/([A-Z])/g,' $1').replaceAll('_',' ')}</dt><dd>{typeof v==='object'?Object.entries(v||{}).map(([a,b])=>`${a}: ${b}`).join(', '):String(v)}</dd></React.Fragment>)}</dl>{data?.files.map(f=><button className="outline" key={f.id} onClick={()=>download(f)}>↓ {f.original_name}</button>)}{data?.quotes.map(q=><p key={q.id}>Quote v{q.version}: {money(q.amount)} · {q.status} {q.customer_note&&`— ${q.customer_note}`}</p>)}{data?.proofs.map(p=><p key={p.id}><a href={`/track/${o.tracking_token}`} target="_blank" rel="noreferrer">Artwork v{p.version}</a> · {p.status} {p.customer_note&&`— ${p.customer_note}`}</p>)}</details>
  {mode==='quotes'&&isAdmin&&!['verified','submitted'].includes(o.payment_status)&&!['completed','cancelled','out_for_delivery'].includes(o.status)&&<form onSubmit={send} className="workflow-form"><label>Confirmed total (ETB), including delivery<input required type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Expected completion (optional)<input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label><label>Quote notes<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={4000} placeholder="Explain the specification, price changes or expected turnaround"/></label><button className="primary" disabled={busy}>{busy?'Sending…':'Confirm price & send for approval'}</button></form>}
  {mode==='proofs'&&!['completed','cancelled','out_for_delivery'].includes(o.status)&&<form onSubmit={send} className="workflow-form"><label>New artwork version<input required type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={e=>setFile(e.target.files[0]||null)}/></label><label>What should the customer check?<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={4000}/></label><button className="primary" disabled={busy||!file}>{busy?`Uploading ${progress}%…`:'Send proof for approval'}</button></form>}
  <p><a className="text-link" href={`/track/${o.tracking_token}`} target="_blank" rel="noreferrer">Open private customer review page ↗</a></p>{error&&<p className="error-text" role="alert">{error}</p>}
 </article>
}
